/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-UTAT_HERON
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_UTAT_HERON_API_H
#define INCLUDED_UTAT_HERON_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_UTAT_HERON_EXPORTS
#define UTAT_HERON_API __GR_ATTR_EXPORT
#else
#define UTAT_HERON_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_UTAT_HERON_API_H */
