/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(esttc_framer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a046fc89b6cb355e0d62a366431e8fef)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/UTAT_HERON/esttc_framer.h>
// pydoc.h is automatically generated in the build directory
#include <esttc_framer_pydoc.h>

void bind_esttc_framer(py::module& m)
{

    using esttc_framer = gr::UTAT_HERON::esttc_framer;


    py::class_<esttc_framer, gr::hier_block2, std::shared_ptr<esttc_framer>>(
        m, "esttc_framer", D(esttc_framer))

        .def(py::init(&esttc_framer::make), D(esttc_framer, make))


        ;
}
