/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(heron_rx_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1a301f9d01ad2f328801f6a113fd6ecf)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/UTAT_HERON/heron_rx_bb.h>
// pydoc.h is automatically generated in the build directory
#include <heron_rx_bb_pydoc.h>

void bind_heron_rx_bb(py::module& m)
{

    using heron_rx_bb = gr::UTAT_HERON::heron_rx_bb;


    py::class_<heron_rx_bb, gr::block, gr::basic_block, std::shared_ptr<heron_rx_bb>>(
        m, "heron_rx_bb", D(heron_rx_bb))

        .def(py::init(&heron_rx_bb::make), D(heron_rx_bb, make))


        ;
}
