/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tagged_stream_bufferer.h) */
/* BINDTOOL_HEADER_FILE_HASH(4a24fcc82fff8eb18d6d3f92d637db93)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/UTAT_HERON/tagged_stream_bufferer.h>
// pydoc.h is automatically generated in the build directory
#include <tagged_stream_bufferer_pydoc.h>

void bind_tagged_stream_bufferer(py::module& m)
{

    using tagged_stream_bufferer = gr::UTAT_HERON::tagged_stream_bufferer;


    py::class_<tagged_stream_bufferer,
               gr::block,
               gr::basic_block,
               std::shared_ptr<tagged_stream_bufferer>>(
        m, "tagged_stream_bufferer", D(tagged_stream_bufferer))

        .def(py::init(&tagged_stream_bufferer::make),
             py::arg("buffer_size"),
             py::arg("packet_len_tag") = "packet_len",
             py::arg("trailer_tag") = "trailer",
             D(tagged_stream_bufferer, make))


        ;
}
