/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(zero_padder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(90168298214f74486d67e79b0fc0814c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/UTAT_HERON/zero_padder.h>
// pydoc.h is automatically generated in the build directory
#include <zero_padder_pydoc.h>

void bind_zero_padder(py::module& m)
{

    using zero_padder = ::gr::UTAT_HERON::zero_padder;


    py::class_<zero_padder, gr::block, gr::basic_block, std::shared_ptr<zero_padder>>(
        m, "zero_padder", D(zero_padder))

        .def(py::init(&zero_padder::make), D(zero_padder, make))


        ;
}
