/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-utat3_9
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_UTAT3_9_API_H
#define INCLUDED_UTAT3_9_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_utat3_9_EXPORTS
#define UTAT3_9_API __GR_ATTR_EXPORT
#else
#define UTAT3_9_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_UTAT3_9_API_H */
